<?php
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
		'key' => 'group_646268dd6b39c',
		'title' => 'Команда',
		'fields' => array(
			array(
				'key' => 'field_646367057a786',
				'label' => 'Фото',
				'name' => 'photo',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => 'Выберите или загрузите фото сотрудника',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'preview_size' => 'post_thumb',
			),
			array(
				'key' => 'field_646367b27a787',
				'label' => 'Должность',
				'name' => 'position',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Введите должность сотрудника',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => 'Введите текст',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_6463681f3ca8a',
				'label' => 'Email',
				'name' => 'email',
				'aria-label' => '',
				'type' => 'email',
				'instructions' => 'Введите электронную почту сотрудника',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'Введите email',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_6462b7b27992b',
				'label' => 'Почему я работаю',
				'name' => 'employee_why',
				'aria-label' => '',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'rows' => 5,
				'placeholder' => 'Введите короткий текст',
				'new_lines' => 'br',
			),
			array(
				'key' => 'field_6462b8770bff8',
				'label' => 'Как и когда я устроился',
				'name' => 'employee_when',
				'aria-label' => '',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'rows' => 5,
				'placeholder' => 'Введите короткий текст',
				'new_lines' => 'br',
			),
			array(
				'key' => 'field_6462b8c4f5a2e',
				'label' => 'Что я делаю в организации',
				'name' => 'employee_what',
				'aria-label' => '',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'rows' => 5,
				'placeholder' => 'Введите короткий текст',
				'new_lines' => 'br',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'team',
				),
			),
			array(
				array(
					'param' => 'widget',
					'operator' => '==',
					'value' => 'block',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );
} );

add_action( 'init', function() {
	register_post_type( 'team', array(
		'labels' => array(
			'name' => 'Команда',
			'singular_name' => 'Команда',
			'menu_name' => 'Команда',
			'all_items' => 'Все Сотрудники',
			'edit_item' => 'Редактировать сотрудника',
			'view_item' => 'Просмотр страницы сотрудника',
			'view_items' => 'View Команда',
			'add_new_item' => 'Add New Команда',
			'new_item' => 'New Команда',
			'parent_item_colon' => 'Parent Команда:',
			'search_items' => 'Search Команда',
			'not_found' => 'No команда found',
			'not_found_in_trash' => 'No команда found in Trash',
			'archives' => 'Команда',
			'attributes' => 'Команда Attributes',
			'insert_into_item' => 'Insert into команда',
			'uploaded_to_this_item' => 'Uploaded to this команда',
			'filter_items_list' => 'Filter команда list',
			'filter_by_date' => 'Filter команда by date',
			'items_list_navigation' => 'Команда list navigation',
			'items_list' => 'Команда list',
			'item_published' => 'Команда published.',
			'item_published_privately' => 'Команда published privately.',
			'item_reverted_to_draft' => 'Команда reverted to draft.',
			'item_scheduled' => 'Команда scheduled.',
			'item_updated' => 'Команда updated.',
			'item_link' => 'Команда Link',
			'item_link_description' => 'A link to a команда.',
		),
		'description' => 'В данном разделе Вы сможете добавлять и редактировать страницы сотрудников компании.',
		'public' => true,
		'show_in_rest' => true,
		'supports' => array(
			0 => 'title',
			1 => 'editor',
			2 => 'revisions',
			3 => 'page-attributes',
			4 => 'thumbnail',
			5 => 'custom-fields',
		),
		'taxonomies' => array(
			0 => 'category',
		),
		'has_archive' => 'team',
		'rewrite' => array(
			'with_front' => false,
			'feeds' => false,
		),
		'delete_with_user' => false,
	) );
} );

